### ISSUE TITLE
Clarify attribute names, or rename package ID

### ISSUE THREAD

**Issue by lg2de** [AArnott/Xunit.StaFact#45]
You are going to release version 1.0. That's great!
But I would like to take the (last) chance to ask whether the naming of the attributes is "as good as possible".

I'm so far a bit confused about the many different versions.
Currently I'm using the `UIFact` because I want to have a thread with `SynchronizationContext` applied, even my use case in **not** a UI thread.

Could you please check again the names, e.g. by creating overview documentation when to use which version?

Finally a recommendation just from my point of view:
* `UIFact` is not really for UI. There are more specific version with `WpfFact` and `WinFormsFact`.
* This attribute could be named like one of the following
  * `SCFact` (synchronizaton context fact, very close to `STAFact`)
  * `ContextFact` (readable, but not fully qualified)

I'll update this list as soon I have new ideas. Maybe you have additional ideas!?

**Comment by AArnott** [comment]
Yes, I am preparing a 1.0 stable release. And you make a valid point about `UIFact` not really being *UI* specific. However, nearly everyone I've observed that deals with `SynchronizationContext` is also dealing with some UI framework, so it's accurate for that scenario, even though it is applicable more broadly than that. I'd rather not rename the attribute at this point because there are already over 100K downloads and I don't want to make upgrading more difficult than necessary.

As far as naming goes, I was most tempted to *rename* the package since hardly anyone is interested in `StaFact` actually -- they really want one of the other attributes that apply a SynchronizationContext. But that too, would probably disrupt more than help. I'm not sure.  Maybe I'll rename and deprecate the original package on nuget.org so folks discover the new one.

**Comment by lg2de** [comment]
IF you EVER rename attributes and/or package, then NOW.

**Comment by AArnott** [comment]
@weltkante Do you have an opinion on the package ID? Should we keep it or rename it? Perhaps to UIFact.Xunit, since I think `Xunit` is now a reserved namespace on nuget.org. Or perhaps Nerdbank.XUnit.UIFact.

**Comment by weltkante** [comment]
Personally I don't have any issues with renaming things. Not speaking for WinForms repo owners but I can do the necessary changes there as well if it becomes necessary, doesn't look like its integrated into arcade infrastructure so should be straightforward to apply any renaming of package references or code.

**Comment by RussKie** [comment]
Thank you for asking, but I don't have a strong opinion. We'll use whatever the name is (assuming you're not planning to delist old versions).

I don't think we use anything but `WinForms*` or `STA*` attributes, so don't have a strong opinion about `UI*` attributes either. Though following the logic laid out above, I'd go for a longer name `SynchronizationContext*` purely for descriptive reasons.

**Comment by AArnott** [comment]
The `[UIFact]` attribute does a little more than just set a `SynchronizationContext`. It also runs the test on an STA thread if on Windows. 
I think I'll keep the names we have, but I'll improve the documentation on the package and attributes to better describe their features and behavior.

**Comment by AArnott** [comment]
Closed with 782b08483d2a9bc47738120133df5d7667c4a5c9.

**Comment by lg2de** [comment]
Would be great to have some documentation in README.md too, e.g. a table with the attributes and its primary intention.
